language: python

python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6.0
install: 
    - pip install -r requirements.txt --use-mirrors
script: 
    - python manage.py test
notifications:
    recipients:
        - wengcc@ihep.ac.cn
    on_success: change
    on_failure: always
    irc:
        channels: 
            - "irc.freenode.org#cloudsafe"
        on_success: change
        on_failure: always
